[package]
name = "psm"
version = "0.1.17"
authors = ["Simonas Kazlauskas <psm@kazlauskas.me>"]
build = "build.rs"
description = "Portable Stack Manipulation: stack manipulation and introspection routines"
keywords = ["stack", "no_std"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang/stacker/"
documentation = "https://docs.rs/psm/0.1.17"
readme = "README.mkd"

[dependencies]

[build-dependencies]
cc = "1.0.2"

[features]
stack_pointer_inline_asm = []